version: '3.8'
services: 
  db:
    build: ./postgres
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  pg_admin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050" 
  app:
    build: ./app
    restart: always
    depends_on:
      - db
    ports:
      - 3000:3000

volumes:
  data:

  